package com.biztracker.ui.theme

import androidx.compose.ui.graphics.Color

val PrimaryLight = Color(0xFF37506A)
val OnPrimaryLight = Color(0xFFFFFFFF)
val PrimaryContainerLight = Color(0xFFDCE4EE)
val OnPrimaryContainerLight = Color(0xFF1B2D43)
val SecondaryLight = Color(0xFF4D6076)
val OnSecondaryLight = Color(0xFFFFFFFF)
val SecondaryContainerLight = Color(0xFFE0E6EE)
val OnSecondaryContainerLight = Color(0xFF2A3E55)
val TertiaryLight = Color(0xFF2F445C)
val OnTertiaryLight = Color(0xFFFFFFFF)
val TertiaryContainerLight = Color(0xFFD9E2EC)
val OnTertiaryContainerLight = Color(0xFF13293F)
val BackgroundLight = Color(0xFFF4F6F8)
val OnBackgroundLight = Color(0xFF0F172A)
val SurfaceLight = Color(0xFFFFFFFF)
val OnSurfaceLight = Color(0xFF111827)
val SurfaceVariantLight = Color(0xFFE3E8EE)
val OnSurfaceVariantLight = Color(0xFF516173)
val SurfaceContainerLowLight = Color(0xFFFAFBFC)
val SurfaceContainerLight = Color(0xFFF1F4F7)
val SurfaceContainerHighLight = Color(0xFFEAF0F6)
val SurfaceContainerHighestLight = Color(0xFFE2EAF2)
val OutlineLight = Color(0xFF9FAEBE)
val OutlineVariantLight = Color(0xFFC7D0DA)
val ErrorLight = Color(0xFFBA1A1A)
val OnErrorLight = Color(0xFFFFFFFF)

val PrimaryDark = Color(0xFFB7C7D8)
val OnPrimaryDark = Color(0xFF20364D)
val PrimaryContainerDark = Color(0xFF425C78)
val OnPrimaryContainerDark = Color(0xFFD9E4EF)
val SecondaryDark = Color(0xFFAFC0D2)
val OnSecondaryDark = Color(0xFF1D334A)
val SecondaryContainerDark = Color(0xFF4A6079)
val OnSecondaryContainerDark = Color(0xFFDCE5EE)
val TertiaryDark = Color(0xFFC0CCD9)
val OnTertiaryDark = Color(0xFF1C3248)
val TertiaryContainerDark = Color(0xFF3F566E)
val OnTertiaryContainerDark = Color(0xFFD8E2EC)
val BackgroundDark = Color(0xFF0F141B)
val OnBackgroundDark = Color(0xFFE4E9EF)
val SurfaceDark = Color(0xFF121820)
val OnSurfaceDark = Color(0xFFE4E9EF)
val SurfaceVariantDark = Color(0xFF2D3744)
val OnSurfaceVariantDark = Color(0xFFC0CAD4)
val SurfaceContainerLowDark = Color(0xFF18202A)
val SurfaceContainerDark = Color(0xFF1F2935)
val SurfaceContainerHighDark = Color(0xFF273240)
val SurfaceContainerHighestDark = Color(0xFF303C4C)
val OutlineDark = Color(0xFF8695A6)
val OutlineVariantDark = Color(0xFF3E4A5A)
val ErrorDark = Color(0xFFFFB4AB)
val OnErrorDark = Color(0xFF690005)
